import { CoreMenu } from "@core/types";

export const menu: CoreMenu[] = [
  {
    id: "home",
    title: "Home",
    translate: "MENU.HOME",
    type: "item",
    icon: "home",
    url: "home",
  },
  {
    id: "sample",
    title: "Sample",
    translate: "MENU.SAMPLE",
    type: "item",
    icon: "file",
    url: "sample",
  },
  {
    id: "user",
    title: "User",
    translate: "",
    type: "collapsible",
    icon: "user",
    children: [
      {
        id: "list",
        title: "List",
        translate: "List ",
        type: "item",
        icon: "circle",
        url: "/apps/user/user-list",
      },
      {
        id: "view",
        title: "View",
        translate: "View",
        type: "item",
        icon: "circle",
        url: "/apps/user/user-view",
      },
      {
        id: "edit",
        title: "Edit",
        translate: "Edit",
        type: "item",
        icon: "circle",
        url: "/apps/user/user-edit",
      },
    ],
  },
  {
    id: "hrm-setting",
    title: "HRM Setting",
    translate: "",
    type: "collapsible",
    icon: "user",
    children: [
      {
        id: "branch",
        title: "Branch",
        translate: "Branch",
        type: "collapsible",
        icon: "circle",
        children: [
          {
            id: "branch-view",
            title: "Branch View",
            translate: "Branch View",
            type: "item",
            icon: "circle",
            url: "/apps/branch/branch-view",
          },
          {
            id: "branch-list",
            title: "Branch List",
            translate: "Branch List",
            type: "item",
            icon: "circle",
            url: "/apps/branch/branch-list",
          },
          {
            id: "branch-edit",
            title: "Branch Edit",
            translate: "Branch Edit",
            type: "item",
            icon: "circle",
            url: "/apps/branch/branch-edit",
          },
        ],
      },
      {
        id: "department",
        title: "Department",
        translate: "Department",
        type: "collapsible",
        icon: "circle",
        children: [
          {
            id: "department-view",
            title: "Department View",
            translate: "Department View",
            type: "item",
            icon: "circle",
            url: "/apps/department/department-view",
          },
          {
            id: "department-list",
            title: "Department List",
            translate: "Department List",
            type: "item",
            icon: "circle",
            url: "/apps/department/department-list",
          },
          {
            id: "department-edit",
            title: "Department Edit",
            translate: "Department Edit",
            type: "item",
            icon: "circle",
            url: "/apps/department/department-edit",
          },
        ],
      },
      {
        id: "position",
        title: "Position",
        translate: "Position",
        type: "collapsible",
        icon: "circle",
        children: [
          {
            id: "position-view",
            title: "Position View",
            translate: "Position View",
            type: "item",
            icon: "circle",
            url: "/apps/position/position-view",
          },
          {
            id: "position-list",
            title: "Position List",
            translate: "Position List",
            type: "item",
            icon: "circle",
            url: "/apps/position/position-list",
          },
          {
            id: "position-edit",
            title: "Position Edit",
            translate: "Position Edit",
            type: "item",
            icon: "circle",
            url: "/apps/position/position-edit",
          },
        ],
      },
    ],
  },
];
